### ISSUE TITLE
No geometry support on update

### ISSUE THREAD

**Issue by luizguilhermefr** [njbarrett/laravel-postgis#100]
Hi,

My environment are: Laravel 5.6, PHP 7.2, PostgreSQL 9.5.13 and Postgis 2.4.2

I am trying to perform a geometry update, however I am getting:

```
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "coordinates" is of type geometry but expression is of type geography\n
LINE 1: ...eometries" set "updated_at" = $1, "coordinates" = public.ST_...\n
                                                             ^\n
HINT:  You will need to rewrite or cast the expression. (SQL: update "geometries" set "updated_at" = 2018-07-02 21:45:40, "coordinates" = public.ST_GeogFromText('MULTIPOLYGON(((-24.918822 -53.472519,-24.946842 -53.521957,-24.984191 -53.508911,-24.918822 -53.472519)))') where "id" = 1)
```

In fact, inspecting the code, I found that, in `PostgisTrait/performInsert()`, there is a verification if the type is geometry or geography, however, in `Builder/asWKT()`, there is no such verification.

I replaced this method hardcoding the parameters and everything seems to work fine.

There is some reason not to do this verification there? If not, I'd be glad to make a PR.

**Comment by njbarrett** [comment]
I believe geometry support was added in https://github.com/njbarrett/laravel-postgis/pull/76/files

It's possible there is a missing test / functionality for updating geometry.

I will gladly review a PR to help fix the issue.
