### ISSUE TITLE
PostGIS with sqlite for unit testing purposes

### ISSUE THREAD

**Issue by loic-lopez** [njbarrett/laravel-postgis#107]
Hello,

I use database memory for unit testing but obviously sqlite don't know `public.ST_GeogFromText` what is it.

It is possible to mock this call or something like that?
Thanks for reply.

**Comment by phaza** [comment]
Postgis is an extension to postgresql, naturally sqlite doesn't know about it.
I think you should mock your entire database layer instead of trying
to mock database functions.

**Comment by loic-lopez** [comment]
@phaza  thanks for reply, Is it possible with laravel ?

**Comment by phaza** [comment]
I haven't used laravel professionally in 3 years, so I can't tell, but
I assume you can somewhow,

**Comment by loic-lopez** [comment]
@phaza  Do you know http://www.gaia-gis.it/?

**Comment by phaza** [comment]
No, and that would be the wrong solution to your problem.
If you use postgresql in production, you should use postgresql in testing too.

**Comment by loic-lopez** [comment]
thanks for advice i will think about that because we have a continuous integration and it's very restrictive

**Comment by phaza** [comment]
You can run a test instance of postgresql, do all testing in
transactions, and just roll them back after each test. Postgresql is
one of the few databases which actually supports this very well.

**Comment by loic-lopez** [comment]
If i understand well:

First step:
`php artisan migrate`
and run tests ?

**Comment by phaza** [comment]
Need to wrap it all in a transaction, which means you should probably run
artisan via code, not command line

**Comment by loic-lopez** [comment]
@phaza thanks for help
