### ISSUE TITLE
Sequence  $lat, $lng  

### ISSUE THREAD

**Issue by tezrik** [njbarrett/laravel-postgis#115]
Why in __construct sequence  $lat, $lng  ?
https://github.com/njbarrett/laravel-postgis/blob/b29f5e288c6e50826c3233b2d9f5cdc83e27bc9a/src/Geometries/Point.php#L11

in json response  $lng, $lat 
https://github.com/njbarrett/laravel-postgis/blob/b29f5e288c6e50826c3233b2d9f5cdc83e27bc9a/src/Geometries/Point.php#L103-L108

**Comment by njbarrett** [comment]
In GeoJSON the correct order is longitude, latitude https://tools.ietf.org/html/rfc7946#appendix-A
