### ISSUE TITLE
Can insert polygon

### ISSUE THREAD

**Issue by YaakovDantas** [njbarrett/laravel-postgis#123]
HI, 

I'm trying to create a Polygon to insert on the DB
`

       $arrayOfPoints = [new Point($lat, $lng)]; // this on a loop

        after the lop

        $linestring= new LineString($arrayOfPoints);
        $Polygon = new Polygon([ $linestring ]);
        return $Polygon;
`

But when try to insert receive this mesage,

`SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "coord" violates not-null constraint`

This is my migration 

`$table->polygon('coordenadas','GEOMETRY', 27700);`

**Comment by YaakovDantas** [comment]
`dd($polygon)`

`
Phaza\LaravelPostgis\Geometries\Polygon^ {#799
  #linestrings: array:1 [
    0 => Phaza\LaravelPostgis\Geometries\LineString^ {#798
      #points: array:50 [
        0 => Phaza\LaravelPostgis\Geometries\Point^ {#751
          #lat: -12.1524491437
          #lng: -47.6087797735
          #alt: null
        }
        1 => Phaza\LaravelPostgis\Geometries\Point^ {#710
          #lat: -12.15248778
          #lng: -47.6087425
          #alt: null
        }
        2 => Phaza\LaravelPostgis\Geometries\Point^ {#709
          #lat: -12.15268889
          #lng: -47.60859444
          #alt: null
        }

`

**Comment by njbarrett** [comment]
Hi @YaakovDantas 
Do you have another column called "coord" ? Your migration refers to a column called "coordenadas"

**Comment by YaakovDantas** [comment]
Hi @njbarrett it's "coordenadas" the right, I put "coord" as example, sorry

**Comment by YaakovDantas** [comment]
@njbarrett I'm saving like this 

`
$data[
...
"coord" => $polygon,
...
];

$this->model->create[$data];

`

Some how this way doesn't work, but doing as your example, works, Do you know why?

**Comment by YaakovDantas** [comment]
@njbarrett solved, I'd have to put in the model "coord" in the "fillable" array as well, Update your example, for future users, thanks by everything.
