### ISSUE TITLE
Query on the use of phoenixgao/laravel-postgres-extended-schema dependency over Bosnadev/Database

### ISSUE THREAD

**Issue by jessedc** [njbarrett/laravel-postgis#52]
Hi, 

I was looking at the differences between the phoenixgao/laravel-postgres-extended-schema project that this project has a dependency and the original [Bosnadev/Database](https://github.com/Bosnadev/Database/) repository this weekend and to me it seems that the Bosnadev repository is more active and up to date than the fork. It was my thought that it _could be_ advantageous to swap one for the other.

As an example , the `\Illuminate\Database\Schema\PostgresBuilder` issue was fixed [a few weeks ago](https://github.com/Bosnadev/Database/commit/3f6c4ee5bfe3f1af39f97d7bf7a9f187e693b2c2) which may negate the need for the main concern behind issue #49 and will in turn close #48 and #46.

I've had a detailed look at the difference between the heads of the two repositorities and apart from additions in Bosnadev and some documentation/travis-ci differences in phoenixgao they appear source compatible. 

Was there any reason why this project originally used phoenixgao over the other?

I've made the change over on [my fork](https://github.com/jessedc/laravel-postgis) and will try things out over the coming weeks but I just thought I'd bring up the topic. 

Cheers!

**Comment by phaza** [comment]
It was to get support for Laravel 5.2. If Bosnadev now supports Laravel 5.2, switching back probably makes sense.

**Comment by jonnybarnes** [comment]
I’ve tried using this with Laravel 5.2 and all the integration tests are working. I vote to change.
