### ISSUE TITLE
Packagist isn’t picking up changes to this repo

### ISSUE THREAD

**Issue by jonnybarnes** [njbarrett/laravel-postgis#55]
It still thinks the latest commit to `master` is `fe880cd`.

**Comment by njbarrett** [comment]
Probably since this was transferred to me, packagist cant find it anymore. I'll register it shortly

**Comment by njbarrett** [comment]
I get this error when trying to add it:

> A package with the name <a href="/packages/phaza/laravel-postgis">phaza/laravel-postgis</a> already exists.
> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. The packages already in that vendor namespace can be found at <a href="/packages/phaza/">phaza</a>
> 

@phaza Do you think you can change this?

**Comment by njbarrett** [comment]
Nevermind, I've just updated composer.json and resubmitted to packagist and it worked. Can you try it out now?

**Comment by phaza** [comment]
Remember to create tags to create new versions. New minor for non-breaking,
new major for breaking changes.

**Comment by phaza** [comment]
Hmm, i think resubmitting is a bad idea. It'll basically create a new package with the same name, but people already using the package wont get updates.

I changed the repo URL on packagist for the phaza/laravel-postgis package, so it should pick up changes now.

P.S
Make sure you add yourselves to the authors array in composer.json. Credit where credit is due.

**Comment by jonnybarnes** [comment]
Looks like its working on packagist: https://packagist.org/packages/phaza/laravel-postgis#dev-master

**Comment by phaza** [comment]
It's working because I changed the repository url (on packagist.org), so it's now tracking this repo instead of my old one.

@njbarrett should probably revert the composer.json change he did and remove his copy on packagist.

**Comment by jonnybarnes** [comment]
Also, @njbarrett’s latest commit has broken Travis

**Comment by njbarrett** [comment]
Ok sorry I messed that up, this is the first time Ive dealt with a repo transfer.
So the namespace will stay the same, Phaza\... and so will the composer.json vendor name? I've updated the travis CI, code climate and coveralls badges as they had stopped working. I've deleted the packagist copy I made and reverted those changes. So everything should be good now I hope.

**Comment by njbarrett** [comment]
I'll tag a new release once everything is confirmed to be working.

**Comment by jonnybarnes** [comment]
Packagist still isn’t picking up the latest commits on `master`, maybe it’ll pick up the next release?

**Comment by njbarrett** [comment]
I just tagged a release, I don't think it's picking it up still. Could be because I changed the API token of the packagist webhook to my own.

@phaza is there a way to add the packagist repo to my account, or can you privately message me your token so I can switch it back to your account.

**Comment by phaza** [comment]
I think I should add you as maintainer on packagist, but I couldn't find your username @njbarrett

**Comment by njbarrett** [comment]
@phaza That's odd, it should just be njbarrett . That's what it says in the menu anyway.

**Comment by phaza** [comment]
Great!
Now you can use your own API key to send webhook updates to packagist.

**Comment by njbarrett** [comment]
Awesome. Looks like it's picking up changes too. Latest commit is accec379af8ceba903ceb10df37beeb9bfb411cc

@jonnybarnes can you confirm it's all good now?

**Comment by phaza** [comment]
Well, I forced an update earlier today, so it's better to verify on the
next commit.

**Comment by jonnybarnes** [comment]
All seems to be working now :)
