### ISSUE TITLE
Laravel v5.1.39 Declaration of Bosnadev createConnection() Error

### ISSUE THREAD

**Issue by Dagiral** [njbarrett/laravel-postgis#56]
PHP 5.6 , Laravel 5.1 .39

Error Exception in ConnectionFactory.php line 14
Declaration of Bosnadev\Database\Connectors
\ConnectionFactory::createConnection() should be compatible with Illuminate\Database\Connectors\ConnectionFactory::c
reateConnection($driver, PDO $connection, $database, $prefix = '', array $config = Array)

Any solution?

**Comment by jonnybarnes** [comment]
I think we fixed this already in the `master` branch, it’ll just need backporting to the `5.1` branch.

The `createConnection()` method just needs to use `$connection`, not `PDO $connection`.

**Comment by njbarrett** [comment]
I've opened PR #57 to fix this

**Comment by njbarrett** [comment]
@jonnybarnes seems the build fails with that change - @Dagiral were you using the `5.1` branch ?

**Comment by adaojunior** [comment]
I'm also having problems with this error

**Comment by njbarrett** [comment]
@adaojunior which Laravel version and which branch are you using?

**Comment by adaojunior** [comment]
4.1.40 and `"phaza/laravel-postgis": "~2.13"`

**Comment by njbarrett** [comment]
@adaojunior My knowledge of this library is that it doesn't support Laravel 4.

In any case you can try the change in this PR and see if it fixes the issue.
https://github.com/njbarrett/laravel-postgis/commit/141329a7f71dec341b753c557dff1462f2841d51

**Comment by adaojunior** [comment]
Sorry, my mistake, it is `5.1.40`

**Comment by njbarrett** [comment]
I have added a new version `2.18` please try updating to this to see if your problem is resolved
