### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [njbarrett/laravel-postgis#58]
Hi, I just trying to replicate the example in `readme.md` but I found:

```
class Location extends Model
{
    protected $postgisFields = [
        Point::class,
        Polygon::class,
    ];

}
```

inaccurate, shouldn't be:

```
class Location extends Model
{
    use PostgisTrait;

    protected $postgisFields = [
        "location"
    ];

}
```

If I use the example, `location` field is returned as string

**Comment by njbarrett** [comment]
I just looked at my recent project and I am doing:
```
    /**
     * Fields using laravel-postgis.
     *
     * @var array
     */
    protected $postgisFields = [
        'lot_bounds' => Polygon::class,
        'lot_center' => Point::class
    ];
```

I believe the docs are incorrect, but I think the above is the correct way. Can you try this?

**Comment by JaakkoTulkki** [comment]
You only need to add the names of the fields; no need to add the class.

**Comment by phaza** [comment]
Thanks, it's absolutely correct that you need to specify the fields, not the types.
