### ISSUE TITLE
Integrating with Backpack Laravel 5.3

### ISSUE THREAD

**Issue by h3ndro** [njbarrett/laravel-postgis#62]
hi ,..great plugin, i wonder how do i integrate with Backpack laravel?i've tried but it gives me DBAL error, could you give me some pointers how to do it?also is it currently compatible with Laravel 5.3?

edit:
add exception msg

`DBALException in AbstractPlatform.php line 423:
Unknown database type geography requested, Doctrine\DBAL\Platforms\PostgreSQL92Platform may not support it.`

**Comment by njbarrett** [comment]
`Unknown database type geography requested` sounds like you don't have PostGIS installed or enabled?
http://www.postgis.net/

**Comment by imzeeshan** [comment]
This is giving me the same error, was working with Laravel 5.2

**Comment by njbarrett** [comment]
I just started using Backpack and was able to reproduce this. I'll try and find a fix shortly.

**Comment by njbarrett** [comment]
Can you please try the new version 3.1.1 that should fix this
