### ISSUE TITLE
Throws error when migrating 

### ISSUE THREAD

**Issue by andresrex** [njbarrett/laravel-postgis#81]
Did nothing but install and when I run the command to migrate it returns the following error:

  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                                       
  Type error: Argument 1 passed to CreateLocationsTable::{closure}() must be an instance of Phaza\LaravelPostgis\Schema\Blueprint, instance of Illuminate\Database\Schema\Blueprint given, cal  
  led in /Library/WebServer/Documents/private/private/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php on line 163

**Comment by njbarrett** [comment]
Your migration class needs to use Phaza\LaravelPostgis\Schema\Blueprint rather than the standard  Illuminate\Database\Schema\Blueprint class

**Comment by jonnybarnes** [comment]
It does have `Phaza\LaravelPostgis\Schema\Blueprint` in the migration sample included in the Readme. But maybe we should add an explicit note as well, someone might skim past that part of the code block if they weren’t expecting it.

**Comment by andresrex** [comment]
Thank you!
