### ISSUE TITLE
problem with MultiPoint with one Point

### ISSUE THREAD

**Issue by siturra** [njbarrett/laravel-postgis#94]
Hi, have a problem:

GeoIO \ WKB \ Parser \ Exception \ ParserException
Parsing failed: $points must contain at least two entries

the_geom is (SRID=32719): 
0101000020CF7F00000000000004131A410000000062865D41

to comment line in Phaza\LaravelPostgis\Geometries\PointCollection.php
line 23:25 **[No Correct Solution]**
//        if (count($points) < 2) {
//            throw new InvalidArgumentException('$points must contain at least two entries');
//        }

result is:
"geom" => MultiPoint {#2945 ▼
      #points: array:1 [▼
        0 => Point {#2946 ▼
          #lat: 5735850.9658061
          #lng: 189293.80895692
        }
      ]

**Comment by nabilelmahiri** [comment]
hi, what i did to solve this problem is, if the number of points is <2, i commented the through exception and add an empty array to the $points array like this:

if (count($points) < 2) {
          //throw new InvalidArgumentException('$points must contain at least two entries');
          array_merge($points, []); 
          
        } 


hope this helps :)

**Comment by pingwiniasty** [comment]
@nabilelmahiri your solution are risky. You cannot modify files in vedor, any update will replace your changes.

@nickbarrettjb Can you look at PR https://github.com/njbarrett/laravel-postgis/pull/40 it fixes this problem. Multipoint may contain only 1 point.

**Comment by njbarrett** [comment]
Released in https://github.com/njbarrett/laravel-postgis/releases/tag/3.6

Thanks
